dist: trusty
sudo: required
language: generic
compiler: gcc
env:
  - ROS_DISTRO=indigo
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  - sudo rosdep init
  - rosdep update; while [ $? != 0 ]; do sleep 1; rosdep update; done
  - sed -i 's@gksudo@sudo@' CMakeLists.txt
  ##
install:
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/
  - ln -s $CI_SOURCE_PATH src/$REPOSITORY_NAME
  - rosdep install -y --from-paths src --ignore-src
  - source /opt/ros/$ROS_DISTRO/setup.bash
script:
  - catkin build

